enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: false

preferAggregateCacheInfo: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.3.1.cjs
