name: "Component: Add Label to PR"
on:
  workflow_call:
    inputs:
      label-name:
        description: "The name of the label to add"
        required: true
        type: string

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Add Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          LABEL: ${{ inputs.label-name }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$REPO/issues/$PR_NUMBER/labels" \
            -f labels[]="$LABEL"
