name: "Component: Comment Handler"
on:
  workflow_call:
    inputs:
      comment-body:
        description: "The exact body of the comment to trigger the action"
        required: true
        type: string
      allowed-associations:
        description: "A comma-separated list of allowed comment author associations"
        required: false
        type: string
        default: "COLLABORATOR,MEMBER,OWNER"
      author-always-allowed:
        description: "Whether the author of the issue/pr is always allowed to trigger the action"
        required: false
        type: boolean
        default: true
    outputs:
      should_run:
        description: "Boolean indicating if the conditions were met"
        value: ${{ jobs.check-comment.outputs.should_run }}

jobs:
  check-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      should_run: ${{ steps.final_check.outputs.should_run }}
    steps:
      - id: check_comment
        name: Check comment contents
        run: |
          if [[ -z "${{ github.event.issue.pull_request }}" || "${{ github.event.comment.body }}" != "${{ inputs.comment-body }}" ]]; then
            echo "Not the command."
            echo "correct_command=false" >> $GITHUB_OUTPUT
          else
            echo "Command found."
            echo "correct_command=true" >> $GITHUB_OUTPUT
          fi
      - id: check_permissions
        name: Check permissions
        if: steps.check_comment.outputs.correct_command == 'true'
        run: |
          if ( [[ "${{ inputs.author-always-allowed }}" == "true" && "${{ github.event.sender.id }}" == "${{ github.event.issue.user.id }}" ]] || \
               [[ ",${{ inputs.allowed-associations }}," == *",${{ github.event.comment.author_association }},"* ]] ); then
            echo "Permissions check passed."
            echo "enough_permissions=true" >> $GITHUB_OUTPUT
          else
            echo "Permissions check failed."
            echo "enough_permissions=false" >> $GITHUB_OUTPUT
          fi

      - id: final_check
        name: Aggregate conditions
        run: |
          if [[ "${{ steps.check_comment.outputs.correct_command }}" == "true" && "${{ steps.check_permissions.outputs.enough_permissions }}" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Add positive reaction on success
        if: steps.final_check.outputs.should_run == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            --method POST -f content='+1'

      - name: Add negative reaction on permission failure
        # This only runs if the command was correct but the permission check failed.
        # The first check in the 'check' step will have already passed.
        if: steps.check_permissions.outputs.enough_permissions == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            --method POST -f content='-1'
