name: "PR Wiki Label"
on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    uses: ./.github/workflows/comment_handler.yml
    secrets: inherit
    with:
      comment-body: "!wiki_label"

  label-pr:
    needs: check-comment
    if: needs.check-comment.outputs.should_run == 'true'
    uses: ./.github/workflows/add_label.yml
    secrets: inherit
    with:
      label-name: "Requires Wiki Update"
